name: UHC
version: '${project.version}'
main: me.frozen.uhc.UHC
api-version: 1.20
depend:
commands:
  moveborder:
    usage: /<command> <size> [time] [centerX] [centerZ]
  uhc:
    usage: </command> <start|border>